# AUTO-REPLY THREADS MATI TOTAL
name: Auto Reply Threads (DISABLED)
on:
  workflow_dispatch:

jobs:
  disabled:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'AUTO-REPLY MATI TOTAL.'
          exit 1
